spring.application.name=jredis
jredis.port=6380
jredis.max-connections=50
jredis.persistence-directory=.
jredis.snapshot-filename=jredis.rdb
jredis.snapshot-interval-seconds=0

logging.level.com.project.jredis=DEBUG

